CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# POSIX API com suporte a threads
CONFIG_POSIX_API=y
CONFIG_DYNAMIC_THREAD=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_DYNAMIC_THREAD_POOL_SIZE=6
CONFIG_POSIX_THREAD_THREADS_MAX=6

# Console via UART (redirecionado para USB CDC no overlay)
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y

# Logs
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=1

# ADC
CONFIG_ADC=y